#!/bin/bash
qemu-system-i386 bin/lOSt.bin\
    -hdb drives/testhd.hd\
    -fda drives/testfd.fd\
    -no-reboot\
    -no-shutdown\
    -audiodev pa,id=audio0 -machine pcspk-audiodev=audio0\
    -m 512M\
    -smp 2\
    -serial mon:stdio
    # -monitor stdio
    # -d int
    # -d trace:*ide*